### PR TITLE
Add set keybinding for default and emacs 

### PR DESCRIPTION
**Pull request by m00nlight**
For user prefer Emacs key bindings. Add a menu to toggle Emacs key binding.

screenshot from 2015-01-20 08 14 28

### CODE REVIEW

**Comment by triska** [comment]
Wow! Many thanks for working on this!

**Comment by JanWielemaker** [comment]
Thanks!   Before merging, just one request: can you turn the selection menu into a submenu of
the *Edit* menu?  Alternatively, we could opt for a *Preferences" modal dialog.  A lot of the infrastructure is in form.js (used in editor.js and gitty.js). Is it stored in the preferences (like semantic highlighting)?

**Comment by m00nlight** [comment]
@JanWielemaker  Move the keybinding setting to preference under the Edit menu. Just one minor problem, how to set the checkbox uncheck by default? I tried to set the default preference "emacs-keybinding" false, and some other way, it does not work. So currently it will use emacs keybinding by default, unless uncheck the "Emacs Keybinding" under the Edit menu.

If this is not acceptable, can you kindly told me how to set the default value of checkbox unchecked, and I will update the pull request.

Thanks

**Comment by m00nlight** [comment]
@JanWielemaker  Done. Set to default keymap by default, and add an checkbox for emacs keybinding under the Edit menu. 

Thanks

swish-screen-shot

**Comment by JanWielemaker** [comment]
Traveling now.  Looks good.  Will take a closer look shorty

**Comment by JanWielemaker** [comment]
Hi m00nlight!  It took much longer than it should have.  I have edited and merged your stuff.  The main change is to use emacs.js from CodeMirror instead of having our own copy.  I merged your commits into a single one to get a clearer view on the impact.

     Thanks!

**Pull request closed without merging**
