### PR TITLE
feat: Upload

### PR DESCRIPTION
**Pull request by kimdk9829**

### CODE REVIEW

**Comment by JanWielemaker** [comment]
I understood these are local changes.    Are you interested in sharing them, so everybody could profit?

**Comment by kimdk9829** [comment]
Of course, I don't care. I'd rather appreciate it! However, there are still a lot of deficiencies in the code.

**Comment by JanWielemaker** [comment]
Whenever you think it is ready!   If you have any questions, you can always try me.   No guarantee though.

**Comment by kimdk9829** [comment]
It's not a very complicated code, so I think I can apply it to the web right away by adding the upload button and the upload process part except for the local part. What do you think?

**Comment by juijeong8324** [comment]
@JanWielemaker 
Hi🤗, we are intern students at the SE Lab of SeoulTech. We are going to add many features to develop Swish during this summer.
So can we share it after this internship?

**Comment by JanWielemaker** [comment]
Sure.   You can also make some noise on the Discourse channel to make people aware and get feedback or ideas.   Good luck!

**Pull request closed without merging**
